### PR TITLE
Initial health check support

### PR DESCRIPTION
**Pull request by eriknelson**
Blocks https://github.com/fusor/cap-ui/pull/3

Initially wanted to do this all client-side. CORS gave me a big, fat, "nope".

### CODE REVIEW

**Review by jmrodri — COMMENTED** [review]
Any reason we're doing this as a script? Seems easy enough to just open a URL from the server and respond appropriately without incurring a separate process.

**Comment by eriknelson** [comment]
@jmrodri Honestly, it was the fastest option that I knew I could get working in time for me to finish the front end for today :)

Makes sense to use golang http, just wasn't familiar with it. I'm happy to keep this unmerged until we have the pure go.

**Comment by jmrodri** [comment]
```
   resp, err := http.Get(host)
   if err != nil {
       fmt.Println(err)
   }
   fmt.Println(resp.StatusCode)
```

**Comment by jmrodri** [comment]
ACK

**Pull request merged**
